### ISSUE TITLE
Cannot find name 'Promise'

### ISSUE THREAD

**Issue by biks152207** [react-native-training/reactxp-starter#1]
I am having issue while running reactXp for web.i get this error message while running "Cannot find name 'Promise'".Thanks in advance

**Comment by cowai** [comment]
+|

**Comment by izzetyildirim** [comment]
You should install required packages beforehand. Simply install following two packages first.
`npm install --save-dev @types/es6-promise`
`npm install --save-dev @types/es6-collections`
Then add corresponding type information to `react-native.d.ts` file as below.
`/// <reference path="../../node_modules/@types/es6-promise/index.d.ts" />`

**Comment by dabit3** [comment]
@izzetyildirim @cowai @biks152207 this should do the trick, let me know if there are any other issues.
